<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{
    public function getInfo()
    {
        return array(
            'count' => $this->createQueryBuilder('artist')
                ->select('count(artist.id)')
                ->getQuery()
                ->getSingleScalarResult()
        );
    }

    public function songAlreadyExists($artistName, $title)
    {
        $data = $this->createQueryBuilder('artist')
            ->where('artist.name = :name')
            ->andWhere('artist.songs.title = :title')
            ->setParameter('name',$artistName)
            ->setParameter('title',$title)
            ->getQuery()
            ->execute();
        return sizeof($data) > 0 ;
    }
}
