<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Song;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * FavouriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteRepository extends EntityRepository
{
	public function isFavourite(User $user, Song $song)
	{
		try {
			$this->createQueryBuilder('favouriteRepository')
				 ->where('favouriteRepository.user = :user')
				 ->andWhere('favouriteRepository.song = :song')
				 ->setParameter('user', $user)
				 ->setParameter('song', $song)
				 ->getQuery()
				 ->getSingleScalarResult();
		} catch (NoResultException $ignore) {
			return false;
		}
		return true;
	}
}
