<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends EntityRepository
{
	public function findAllQuery()
	{
		return $this->createQueryBuilder('s');
	}

	public function getInfo()
	{
		return array(
			'count' => $this->createQueryBuilder('song')
							->select('count(song.id)')
							->getQuery()
							->getSingleScalarResult()
		);
	}

	/**
	 * @param $songTitle
	 * @param array $artistNames
	 *
	 * @return \Doctrine\ORM\QueryBuilder
	 *
	 */
	public function findBySongAndArtist($songTitle, $artistNames)
	{
		return $this->createQueryBuilder('song')
					->join('song.artists', 'artists')
					->where('song.title = :title')
					->andWhere('artists.name IN(:artistNames)')
					->setParameter('title', $songTitle)
					->setParameter('artistNames', $artistNames)
					->getQuery()
					->execute();
	}

	/**
	 * @param int $max
	 *
	 * @param null $artistId
	 *
	 * @return array
	 */
	public function getRandomSongs($max = 20, $artistId = null)
	{
		$query = $this->createQueryBuilder('song')
					  ->where('song.published = true');
		if ($artistId) {
			$songs = $this->getSongsOfArtist($artistId);
			$ids   = array_column($songs, 'id');

			$query->where('song.id NOT IN(:ids)')
				  ->setParameter('ids', $ids);
		}
		$songs = $query->getQuery()
					   ->execute();
		shuffle($songs);
		return array_slice($songs, 0, $max);
	}

	/**
	 * @param $max
	 *
	 * @return mixed
	 */
	public function topDownloads($max)
	{
		return $this->createQueryBuilder('song')
					->where('song.published = true')
					->addOrderBy('song.countDownload', 'DESC')
					->setMaxResults($max)
					->getQuery()
					->execute();
	}

	public function newReleases($limit)
	{
		return $this->createQueryBuilder('song')
					->where('song.isNew = :isNew')
					->setParameter('isNew', true)
					->orderBy('song.publishedAt')
					->setMaxResults($limit)
					->getQuery()
					->execute();
	}

	/**
	 * Search Song by title and artist
	 *
	 * @param $text
	 *
	 * @param int $limit
	 *
	 * @return mixed
	 */
	public function search($text, $limit = 200)
	{
		$texts        = explode(' ', $text);
		$queryBuilder = $this->createQueryBuilder('song')
							 ->join('song.artists', 'artists');
		foreach ($texts as $text) {
			$queryBuilder->orWhere('upper(song.title) LIKE :text')
						 ->orWhere('upper(artists.name) LIKE :text')
						 ->orWhere('upper(artists.lastname) LIKE :text');

		}
		return $queryBuilder
			->setMaxResults($limit)
			->setParameter(':text', '%' . strtoupper($text) . '%')
			->getQuery()
			->execute();
	}

	private function getSongsOfArtist($artistId)
	{
		return $this->createQueryBuilder('song')
					->select('song.id')
					->join('song.artists', 'artists')
					->where('artists.id = :id')
					->setParameter('id', $artistId)
					->getQuery()
					->execute();
	}
}
