<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRepository extends EntityRepository
{
	public function findAllQuery()
	{
		return $this->createQueryBuilder('s');
	}

	public function getInfo()
	{
		return array(
			'count' => $this->createQueryBuilder('song')
							->select('count(song.id)')
							->getQuery()
							->getSingleScalarResult()
		);
	}

	/**
	 * @param $songTitle
	 * @param $artistName
	 *
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	public function findBySongAndArtist($songTitle, $artistName)
	{
		return $this->createQueryBuilder('song')
					->join('song.artist', 'artist')
					->where('song.title = :title')
					->andWhere('artist.name = :artistName')
					->setParameter('title', $songTitle)
					->setParameter('artistName', $artistName)
					->getQuery()
					->execute();
	}

	/**
	 * @param int $max
	 *
	 * @return array
	 */
	public function getRandomSongs($max = 20)
	{
		$songs = $this->createQueryBuilder('song')
					  ->where('song.published = true')
					  ->getQuery()
					  ->execute();
		shuffle($songs);
		return array_slice($songs, 0, $max);
	}

	/**
	 * @param $max
	 *
	 * @return mixed
	 */
	public function topDownloads($max)
	{
		return $this->createQueryBuilder('song')
					->where('song.published = true')
					->addOrderBy('song.countDownload', 'DESC')
					->setMaxResults($max)
					->getQuery()
					->execute();
	}

	public function newReleases($max)
	{
		return $this->createQueryBuilder('song')
					->where('song.published = true')
					->orderBy('song.publishedAt')
					->setMaxResults($max)
					->getQuery()
					->execute();
	}

	/**
	 * Search Song by title and artist
	 *
	 * @param $text
	 *
	 * @return mixed
	 */
	public function search($text)
	{
		$texts        = explode(' ', $text);
		$queryBuilder = $this->createQueryBuilder('song')
							 ->join('song.artists', 'artists');
		foreach ($texts as $text) {
			$queryBuilder->orWhere('upper(song.title) LIKE :text')
						 ->orWhere('upper(artists.name) LIKE :text')
						 ->orWhere('upper(artists.lastname) LIKE :text');

		}
		return $queryBuilder
			->setParameter(':text', '%' . strtoupper($text) . '%')
			->getQuery()
			->execute();
	}
}
