imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            json: \Doctrine\DBAL\Types\JsonArrayType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            softdeleteable: true
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'
#        pagination: AppBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig'
nelmio_api_doc: ~

jms_serializer:
    visitors:
        json:
            options: JSON_UNESCAPED_UNICODE
fos_user:
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
rch_jwt_user:
    user_class: AppBundle\Entity\User # your user class (required)
    user_identity_field: email        # the property used as authentication credential (tied to password)
    passphrase: obon                # the passphrase of your RSA private key

nelmio_cors:
        paths:
            '^/':
                allow_credentials: true
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth', 'Content-Type','Authorization','Origin', 'X-Requested-With', 'Content-Type', 'Accept']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
                max_age: 3600
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            logging: "%kernel.debug%"

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]


sonata_admin:

    title: Muzyka
    title_logo: /public/img/logo.png
    templates:
        layout:              ApplicationSonataAdminBundle::standard_layout.html.twig
        edit:                ApplicationSonataAdminBundle::base_edit.html.twig