app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_lyrics:
    resource: "@LyricsBundle/Controller/"
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
security_register:
    path:    /register
    defaults: { _controller: RCHJWTUserBundle:Security:register }
    requirements:
        methods: POST

security_login:
    path:    /login
    defaults: { _controller: RCHJWTUserBundle:Security:login }
    requirements:
        methods: POST

security_oauth_login:
    path:    /api/oauth/login
    defaults: { _controller: AppBundle:Security:loginFromOAuthResponse }
    requirements:
        methods: POST

security_refresh_token:
    path:     /refresh_token
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    requirements:
        methods: POST