app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_lyrics:
    resource: "@LyricsBundle/Controller/"
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
security_register:
    path:    /register
    defaults: { _controller: RCHJWTUserBundle:Security:register }
    requirements:
        methods: POST

security_login:
    path:    /login
    defaults: { _controller: RCHJWTUserBundle:Security:login }
    requirements:
        methods: POST

security_oauth_login:
    path:    /api/oauth/login/{provider}
    defaults: { _controller: AppBundle:Security:loginFromOAuthResponse }
    requirements:
        methods: POST

security_refresh_token:
    path:     /refresh_token
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    requirements:
        methods: POST

fos_user_security_login:
    path:  /muz-admin/login/
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:  /muz-admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:  /muz-admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /muz-admin


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /muz-admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /muz-admin