app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_lyrics:
    resource: "@LyricsBundle/Controller/"
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
rch_jwt_user:
    resource: "@RCHJWTUserBundle/Resources/config/routing.yml"