security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Signin
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                check_path: /login
                require_previous_session: false
                username_parameter: email
                password_parameter: password
                #success_handler: lexik_jwt_authentication.handler.authentication_success
                success_handler: app.lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        # Signup
        register:
            pattern: ^/register
            anonymous: true
            stateless: true
        # Refresh token
        refresh:
            pattern:  ^/refresh_token
            stateless: true
            anonymous: true
        # API (secured via JWT)
        api:
            pattern:   ^/apis
            stateless: true
            lexik_jwt: ~

        admin:
            pattern:            /muz-admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /muz-admin/login/
                use_forward:    false
                check_path:     /muz-admin/login_check
                failure_path:   null
                default_target_path:            /muz-admin/dashboard
            logout:
                path:           /muz-admin/logout
            anonymous:          true

    access_control:
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/refresh_token, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apis, role: IS_AUTHENTICATED_FULLY }


        - { path: ^/muz-admin/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/muz-admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/muz-admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/muz-admin/, role:[ROLE_SUPER_ADMIN] }

