# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    admin.song:
        class: AppBundle\Admin\SongAdmin
        arguments: [~, AppBundle\Entity\Song, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Song }

    app.song:
        class: AppBundle\Services\SongService
        arguments: ["@doctrine.orm.entity_manager"]