# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
services:
  app.kernel_response.listener:
    class:  AppBundle\EventListener\KernelResponseListener
    tags:
      - { name: kernel.event_listener, event: kernel.response, method:  onKernelResponse}