services:
#    info_company.example:
#        class: Info\CompanyBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    rch_jwt_user.credential_fetcher:
        class: RCH\JWTUserBundle\Services\CredentialFetcher
        arguments: ["@request_stack","@validator"]

    app.lexik_jwt_authentication.handler.authentication_success:
        class: AppBundle\Security\Http\Authentication\AuthenticationSuccessHandler
        arguments: ["@lexik_jwt_authentication.jwt_manager", "@event_dispatcher"]
        tags:
            - { name: monolog.logger, channel: security }

    app_formatter.song:
        class: AppBundle\Formatter\SongFormatter
        arguments:  ['@security.token_storage','@doctrine.orm.default_entity_manager', '@service_container']
    app_formatter.artist:
        class: AppBundle\Formatter\ArtistFormatter
        arguments:  ['@app_formatter.song']
    app_formatter.favourite:
        class:  AppBundle\Formatter\FavouriteFormatter
        arguments:  ['@app_formatter.song']
    app_formatter.history:
        class: AppBundle\Formatter\HistoryFormatter
        arguments:  ['@app_formatter.song']
    app_formatter.user:
        class: AppBundle\Formatter\UserFormatter
    app_formatter.playlist:
        class:  AppBundle\Formatter\PlaylistFormatter
        arguments:  ['@app_formatter.song']


    app.admin.artist:
        class: AppBundle\Admin\ArtistAdmin
        arguments: [~, AppBundle\Entity\Artist, AppBundle:ArtistAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Ырчылар, label: Ырчылар, on_top : true, icon: '<i class="fa fa-user-circle-o"></i>' }

    app.admin.song:
        class: AppBundle\Admin\SongAdmin
        arguments: [~, AppBundle\Entity\Song, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Ырлар, label: Ырлар, on_top : true, icon: '<i class="fa fa-music"></i>' }

    app.admin.favourite:
        class: AppBundle\Admin\FavouriteAdmin
        arguments: [~, AppBundle\Entity\Favourite, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Тренд, label: Тренд, on_top : true, icon: '<i class="fa fa-line-chart"></i>'  }

    app.admin.genre:
        class: AppBundle\Admin\GenreAdmin
        arguments: [~, AppBundle\Entity\Genre, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Жанр, label: Жанр, on_top : true, icon: '<i class="fa  fa-heart"></i>'  }


    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Колдонуучулар, label: Колдонуучулар, on_top : true, icon: '<i class="fa fa-users"></i>'  }