<?php

namespace LyricsBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{
    public function getInfo()
    {
        return array(
            'count' => $this->createQueryBuilder('artist')
                ->select('count(artist.id)')
                ->getQuery()
                ->getSingleScalarResult()
        );
    }
}
